development:
  adapter: mysql2
  encoding: utf8
  database: tipsy_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: tipsy_test
  host: localhost
  username: root
  password:
